var data = [
	{
		id: 0,
		name: 'Opening Ceremony',
		org: 'DevCon Yangon',
		position: 'Working Group',
		topic: 'Opening Ceremony',
		summary: '',
		day: 1,
		room: 'Conference Room',
		time: '8:30 AM - 9:45 AM',
		favorite: false,
		photo: true
	},
	{
		id: 1,
		name: 'U Win Htein Win',
		org: 'Guesto Institute',
		position: 'Founder & Principal',
		topic: 'Keynote Speech',
		summary: '',
		day: 1,
		room: 'Conference Room',
		time: '9:45 AM - 10:00 AM',
		favorite: false,
		photo: true
	},
	{
		id: 2,
		name: 'Phone Pyae Oo',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Technopreneurs, not just Developers',
		summary: '',
		day: 1,
		room: 'Conference Room',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: true
	},
	{
		id: 3,
		name: 'Ko Ko Ye',
		org: 'Ubuntu Myanmar',
		position: 'LoCo Team',
		topic: 'Business for Customized OS',
		summary: '',
		day: 1,
		room: 'Conference Room',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 4,
		name: 'Tin Maung Maung Yin',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Building Better Cross-Platform Mobile Apps Faster',
		summary: 'This topic will discuss and present about how to develop cross-platform mobile apps (native or web-based) faster with effective and efficient development environment.',
		day: 1,
		room: 'Conference Room',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 5,
		name: 'Ei Maung',
		org: 'Fairway Web',
		position: 'Project Manager',
		topic: 'Software Project Management 101',
		summary: 'Going to present basic software project management concepts and practices such as iterative development, SCRUM, code review, issue tracking, functional spec and project schedule.',
		day: 1,
		room: 'Conference Room',
		time: '2:00 PM - 3:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 6,
		name: 'Ye Thura Thet',
		org: 'Organization',
		position: 'Unknown',
		topic: "Collecting, Visualizing and Analyzing Web Application Logs: The Programmer's Way",
		summary: "Web application logs can tell us the story about how the application is used after deployment. Due to the obscurity and complexity of various log formats, it is often hard for programmers to collect, process and analyze the logs to capture the stories. The presentation discusses open sources tools and ecosystems such as Elastic Search, Logstash and Kibana o collect, process, visualize and analyze logs in web applications.",
		day: 1,
		room: 'Conference Room',
		time: '3:00 PM - 4:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 7,
		name: 'Aung Soe Moe',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Robotic Frameworks',
		summary: '',
		day: 1,
		room: 'Conference Room',
		time: '4:00 PM - 5:00 PM',
		favorite: false,
		photo: true
	},

	{
		id: 8,
		name: 'Noe Noe',
		org: 'Organization',
		position: 'Unknown',
		topic: 'တစ်ပင်တိုင် ၃၆၀',
		summary: "The way how to negotiate between geek technicians  and  newbie users who don't have experience on using IT Products especially App",
		day: 1,
		room: 'Room 205',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: true
	},
	{
		id: 9,
		name: 'Khine Wai Oo',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Systems for the age of the Internet of Things',
		summary: 'We often hear the word, "IoT" (Internet of Things) recently. As a system developer, we need to understand reasons why the IoT became popular and background for the age of IoT. And we need to know what kinds of systems are suitable for the age. We would like to talk about IoT features and systems desired for the age of IoT with demos.',
		day: 1,
		room: 'Room 205',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 10,
		name: 'Ko Ko Ye',
		org: 'Ubuntu Myanmar',
		position: 'LoCo Team',
		topic: 'IoT for GPIO Zer',
		summary: '',
		day: 1,
		room: 'Room 205',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 11,
		name: 'Sai Tin Min Lu',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Secure Coding or Code with Security',
		summary: 'Developer today are very lazy to secure code and this is the main vulnerability to hack the system. To make user code secure is very important and there are many standard to need to obey to write code. I will show you the knowledge area of secure code and the guidelines to need to do for your code. In the technology age, without the security knowledge you can’t be a good Developer. So security is very important now day.',
		day: 1,
		room: 'Room 205',
		time: '2:00 PM - 3:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 12,
		name: 'Myat Min Soe',
		org: 'Organization',
		position: 'Unknown',
		topic: 'The Journey of a Mobile Developer',
		summary: '',
		day: 1,
		room: 'Room 205',
		time: '3:00 PM - 4:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 13,
		name: 'Wai Phyo Thwin',
		org: 'Organization',
		position: 'Unknown',
		topic: '3D Printing Technology',
		summary: '',
		day: 1,
		room: 'Room 205',
		time: '4:00 PM - 5:00 PM',
		favorite: false,
		photo: true
	},

	{
		id: 14,
		name: 'Win Htoo Myint',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Next Hot Key Technology of the Web Application',
		summary: "To know where we are going, you need to look back our technology history. Who can tell about of our foot-step? It’s just your work. You already have been heard about of ephemeral technologies. In this place, I have to ask you one thing that it can make to apply your development life and your productivity. I think that we are going same ways in here. To penetrate our technology what should we know and what should understand? Today technologies consumers no want to install on their computer and they don’t like to use the controlling with a window app, mean that web browser. As a developer not want to manual installation in all of his clients. Okie, What should we do? What is our solution? I would like to tell the about of look and feel desktop app technology, it’s simultaneously capturing the benefit of a “thin client”. It’s really different with mobile app. I would like to share my hocus-pocus with different thinking technology including technology, management, cost-effective, user convenience in his work-desks and how to useful in a fat-clients (high performance and high productivity). This is bridge between web app and window app that it’s providing the snappy look and feel inherence to most of our thinking.",
		day: 1,
		room: 'Room 203',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: false
	},
	{
		id: 15,
		name: 'Thuya Myo Nyunt',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Function the Ultimate (JavaScript)',
		summary: 'JavaScript is the popular amount Today Web. But the things you know about JavaScript might be nasty, unstable API such as. But there are good part and I want to show you about some good part of it.  As the JavaScript Influenced by Scheme (functional language) we can write functional programming with it. Different from other OOP Language, the functions are the first class citizen in JavaScript.',
		day: 1,
		room: 'Room 203',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 16,
		name: 'Ye Kyaw Thu',
		org: 'Organization',
		position: 'Unknown',
		topic: 'A Large-scale Study of Statistical Machine Translation',
		summary: 'We conducted the first large-scale evaluation of the quality of automatic translation between Myanmar and twenty one other languages, in both directions. The experiments were carried out using three different statistical machine translation approaches: phrase-based, hierarchical phrase-based, and the operation sequence model (OSM). In addition three different segmentation schemes for Myanmar were studied, these were syllable segmentation, maximum matching word segmentation with a dictionary and supervised word segmentation. I will present the performance of automatic machine translation measured in terms of both the BLEU and RIBES scores. An analysis of the experimental results indicated that Kendall’s tau may be directly used as a means of selecting an appropriate machine translation approach for a given language pair.',
		day: 1,
		room: 'Room 203',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 17,
		name: 'Win Pa Pa',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Developing Myanmar Automatic Speech Recognition and Text to Speech Systems',
		summary: 'The primary goal of this development is to develop the first industrially applicable automatic speech recognition (ASR) and text-to-speech systems (TTS) for the Myanmar language. This development is a part of research collaboration between the National Institute of Information and Communications Technology (NICT), Japan and the University of Computer Studies Yangon (UCSY), Myanmar. The overall process of developing these Myanmar ASR and TTS systems, at the stages of data preparation, recording, pronunciation lexicon building, grapheme-to-phoneme converter (G2P) development and system evaluation will be presented. The final results of this work will be incorporated into the "VoiceTra" industrial speech-to-speech translation application developed by the Universal Speech Translation Advanced Research (U-STAR) group.',
		day: 1,
		room: 'Room 203',
		time: '2:00 PM - 3:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 18,
		name: 'College Phyoth',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Organizations Security',
		summary: 'Discussion about security system within organization preocedures to follow when cyber security is under attacked, network protocol security and database security and its threats when it is hacked.',
		day: 1,
		room: 'Room 203',
		time: '3:00 PM - 4:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 19,
		name: 'Ye Lin Kyaw',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Introduction to Human Computer Interaction',
		summary: '',
		day: 1,
		room: 'Room 203',
		time: '4:00 PM - 5:00 PM',
		favorite: false,
		photo: false
	},

	{
		id: 20,
		name: 'Cho Zin Wint',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Women in IT Industry',
		summary: 'Opening - Special Highlight',
		day: 2,
		room: 'Conference Room',
		time: '9:00 AM - 10:00 AM',
		favorite: false,
		photo: false
	},
	{
		id: 21,
		name: 'Phyo Zaw Tun',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Better Frontend Development Quality Beyond Bootstrap',
		summary: 'Entry stage of Bootstrap is easy to understrand than all other backend development technology. In the same time to get premium quality front end design quality is difficult like all other development challenge. I hope my topic would be cover to developer who already understrand Bootstrap and who facing challenge while trying to make premium quality result.',
		day: 2,
		room: 'Conference Room',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: false
	},
	{
		id: 22,
		name: 'Zaw Min Aung',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Responsibility & Developing Mindset',
		summary: "We have full responsibility for our country's future. So, our young developers must concentrate on developing process with obligation to prove that what can we do among other countries.",
		day: 2,
		room: 'Conference Room',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 23,
		name: 'Wai Lin Tun',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Developer တစ်ယောက် အမှား တစ်သိန်း',
		summary: '',
		day: 2,
		room: 'Conference Room',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: true
	},
	
	{
		id: 27,
		name: 'Thar Htet',
		org: 'Zwenexsys',
		position: 'CEO',
		topic: 'Making Unicode Friendly Mobile Apps',
		summary: '',
		day: 2,
		room: 'Room 205',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: true
	},
	{
		id: 28,
		name: 'Ye Linn Wai',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Move to iOS',
		summary: '',
		day: 2,
		room: 'Room 205',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 29,
		name: 'Htoo Myint Naung',
		org: 'Technomation',
		position: 'CEO',
		topic: 'Computerized Secret Hiding',
		summary: '',
		day: 2,
		room: 'Room 205',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: true
	},

	{
		id: 30,
		name: 'Thet Aung Soe',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Project Management for ICT Infrastructure Implementation',
		summary: '',
		day: 2,
		room: 'Room 203',
		time: '10:00 AM - 11:00 AM',
		favorite: false,
		photo: false
	},
	{
		id: 31,
		name: 'Ye Myat Min',
		org: 'Organization',
		position: 'Unknown',
		topic: 'Getting Your First Client as a Freelancer',
		summary: "Are you the kind of person who wants to work with 'own time, own target'? Just finished university and still figuring out what to do next? Or, are you just thinking to save enough money for your future? Freelancing for other people can be a great solution to this. Everything that will be in this presentation is through personal experience.",
		day: 2,
		room: 'Room 203',
		time: '11:00 AM - 12:00 PM',
		favorite: false,
		photo: false
	},
	{
		id: 32,
		name: 'Soe Thiha Naung',
		org: 'Myanmar Links',
		position: 'CEO',
		topic: 'Experiences on Teaching and Mentoring Technology in Myanmar',
		summary: 'နည်းပညာနဲ့ ပတ်သက်ပြီး အခြေခံပညာရေးတွေမှာ ရေခံမြေခံမကောင်းခဲ့တဲ့အတွက် နည်းပညာ သင်ကြားရေးအပိုင်းမှာ တကယ် တတ်ကျွမ်းတဲ့ ပညာရှင်တွေ ထွက်ပေါ်လာဖို့၊ ပူးပေါင်းဆောင်ရွက်နိုင်ဖို့၊ ပါရမီရှင်တွေ ထွက်ပေါ်လာဖို့ဆိုတာ သင်ကြားနည်း နည်းစနစ်ပေါင်းစုံကို သင့်တော်သလို အသုံးချပြီး အချိန်နဲ့ တစ်ပြေးညီ၊ လိုအပ်ချက်နဲ့အညီ ပြောင်းလဲ အသုံးပြုနိုင်ဖို့ လိုပါတယ်။ "Experiences on mentoring and teaching technology in Myanmar" ဆိုတာ ကျွန်တော် နည်းပညာသင်ဆရာ တစ်ယောက်အနေနဲ့ ဖြတ်သန်းခဲ့တဲ့ အတွေ့အကြုံတွေထဲက ထွက်ပေါ်လာတဲ့ အတွေ့အကြုံဆိုင်ရာ ဟောပြောဆွေးနွေးချက်တစ်ရပ်ပါ',
		day: 2,
		room: 'Room 203',
		time: '1:00 PM - 2:00 PM',
		favorite: false,
		photo: true
	},

	{
		id: 24,
		name: 'Panel Discussion',
		org: 'DevCon Yangon',
		position: 'Working Group',
		topic: 'Oblivious Transition (Moving Into Unicode-era)',
		summary: 'Dr. Tun Thura Thet, Dr. Zaw Tun, Htoo Myint Naung, Soe Naung Win. Moderated by Thar Htet.',
		day: 2,
		room: 'Conference Room',
		time: '2:00 PM - 3:00 PM',
		favorite: false,
		photo: true
	},
	{
		id: 25,
		name: 'Townhall Meeting',
		org: 'DevCon Yangon',
		position: 'Working Group',
		topic: 'Open Discussion',
		summary: '',
		day: 2,
		room: 'Conference Room',
		time: '3:00 PM - 4:30 PM',
		favorite: false,
		photo: true
	},
	{
		id: 26,
		name: 'Closing Ceremony',
		org: 'DevCon Yangon',
		position: 'Working Group',
		topic: 'Closing Ceremony',
		summary: '',
		day: 2,
		room: 'Conference Room',
		time: '4:30 PM - 5:00 PM',
		favorite: false,
		photo: true
	}
];